### ISSUE TITLE
Completion doesn't append to the current item

### ISSUE THREAD

**Issue by wroyca** [NeViRAIDE/nekifoch.nvim#2]
Hello, thank for this plugin!

Using it, it appear that nvim default completion will not append the current item; instead, it will continue to insert, which makes it difficult to try many fonts on the fly:

[Screencast from 2024-04-16 10-02-09.webm](https://github.com/RAprogramm/nekifoch/assets/91024200/8e8bb9a3-23bd-47b5-938c-91abdea4893e)

**Comment by RAprogramm** [comment]
> Hello, thank for this plugin!
> 
> Using it, it appear that nvim default completion will not append the current item; instead, it will continue to insert, which makes it difficult to try many fonts on the fly:
> 
> [Screencast from 2024-04-16 10-02-09.webm](https://github.com/RAprogramm/nekifoch/assets/91024200/8e8bb9a3-23bd-47b5-938c-91abdea4893e)
> 
> 

Thank you for issue. I got you.  I'll try to fix it asap!

**Comment by RAprogramm** [comment]
https://github.com/RAprogramm/nekifoch/assets/70325462/f4c1d1d0-e66f-4157-85d3-f4d01f73bdeb

check this out!
i tried to reproduce your situation, but behavior is good.
is the problem could be in your `<TAB>` or `<ENTER>` keybinding?

**Comment by wroyca** [comment]
> neki_check.mp4
> 
> check this out! i tried to reproduce your situation, but behavior is good. is the problem could be in your `<TAB>` or `<ENTER>` keybinding?

Thank for looking into it!

> i tried to reproduce your situation, but behavior is good.

The situation occurs only when resuming completion. That is, selecting a font, deleting a letter from the font name, then pressing tab to bring up completion again. Cycling alone is fine; Here's a dummy example, say you have two similar fonts:

* foo
* foobar

In the command line, type "Nekifoch set_font f," then press tab to bring up the completion items "foo" and "foobar." Cycle to "foobar" with the completion and then close it by, say, deleting the "bar" characters. At this point, you're back with "foo" again. Press tab to complete, which will trigger the faulty behavior (e.g., "foofoobar" instead of "foobar," or "foofoo" instead of "foo," or "foounrelatedfontnamehere")

---

In case you can't reproduce, I don't have any special bindings or keymaps. I mostly run a pretty vanilla configuration when it comes to keybinds, and I don't have any options (as far as I know) that would affect the completion options (see https://github.com/wroyca/dotfiles/blob/4ab2ae28e45857a71bcca994115b4bdb5b2a4259/dot_config/nvim/init.lua#L14-L49) but I do run neovim nightly so that may play a role here \;)

**Comment by wroyca** [comment]
> > neki_check.mp4
> > check this out! i tried to reproduce your situation, but behavior is good. is the problem could be in your `<TAB>` or `<ENTER>` keybinding?
> 
> Thank for looking into it!
> 
> > i tried to reproduce your situation, but behavior is good.
> 
> The situation occurs only when resuming completion. That is, selecting a font, deleting a letter from the font name, then pressing tab to bring up completion again. Cycling alone is fine; Here's a dummy example, say you have two similar fonts:
> 
>     * foo
> 
>     * foobar
> 
> 
> In the command line, type "Nekifoch set_font f," then press tab to bring up the completion items "foo" and "foobar." Cycle to "foobar" with the completion and then close it by, say, deleting the "bar" characters. At this point, you're back with "foo" again. Press tab to complete, which will trigger the faulty behavior (e.g., "foofoobar" instead of "foobar," or "foofoo" instead of "foo," or "foounrelatedfontnamehere")

"In case you can't reproduce, I don't have any special bindings or keymaps. I mostly run a pretty vanilla configuration when it comes to keybinds, and I don't have any options (as far as I know) that would affect the completion options (see https://github.com/wroyca/dotfiles/blob/4ab2ae28e45857a71bcca994115b4bdb5b2a4259/dot_config/nvim/init.lua#L14-L49) but I do run neovim nightly so that may play a role here \;)

**Comment by RAprogramm** [comment]
Oh! Now I'm understand.  Give me little bit more time

**Comment by RAprogramm** [comment]
@wroyca , please check this out!

**Comment by wroyca** [comment]
> @wroyca , please check this out!

Thank for the changes! (and wow, that's quite a lot of changes :exploding_head:)

From my tests, the font is now properly replaced so long as the cursor is on the first word, **but** then breaks if the cursor is on the second (and third, and so forth...) word:

https://github.com/RAprogramm/nekifoch/assets/91024200/00b1d4d5-af15-4c3b-ac6f-9ac967f68f4d

My guess is that it recognizes the first word as the font name, but then something breaks upon encountering a whitespace, and it proceeds to recognize the first word and second word as two different fonts (even though it's only one font)

**EDIT:** I wonder if that's also Neovim's default behavior? There's not much to test the completion on similar to a "name with whitespace" - if so one solution perhaps would be to sanitize the font name and replace whitespace with _ for neovim (then switch back to whitespace once applying)

**Comment by RAprogramm** [comment]
Something wrong. Is not last changes on your record. Are you use 1.2.3. Release?

**Comment by wroyca** [comment]
> Something wrong. Is not last changes on your record. Are you use 1.2.3. Release?

Ah! nice catch, indeed, turn out it was using a cached version, everything work fine :partying_face:
